/* Nastro Blu catalog — packaging-complete product registry */
window.NASTRO_BRAND = {
  name: "Nastro Blu",
  legalName: "Nastro Blu — Eat Better",
  tagline: "Know Your Farmer. Know Your Food.",
  email: "nastroblu.eatbetter@gmail.com",
  whatsapp: "919063048255",
  phone: "+91 40 4540 8385",
  whatsappDisplay: "+91 90630 48255",
  instagram: "https://www.instagram.com/nastroblu.eatbetter/",
  address: "2-2-18/15/C, Plot No-10, D.D. Colony, Bagh Amberpet, Hyderabad – 500013",
  fssai: "Available on pack / ask in store",
  city: "Hyderabad",
};

window.NASTRO_CATALOG = {
  categories: [
    { id: "all", name: "All Products", icon: "✦" },
    { id: "produce", name: "Naturally Grown Produce", icon: "🌿" },
    { id: "oils", name: "Cold Pressed Oils", icon: "🫒" },
    { id: "spices", name: "Kerala Spices", icon: "🌶" },
    { id: "honey", name: "Honey", icon: "🍯" },
    { id: "dryfruits", name: "Kashmiri Dry Fruits", icon: "🥜" },
    { id: "sweets", name: "Traditional Sweets & Snacks", icon: "🍬" },
    { id: "ghee", name: "Dairy & Ghee", icon: "🧈" },
  ],
  products: [
    {
      id: "kala-namak-rice",
      name: "Kala Namak Rice",
      brand: "Nastro Blu",
      category: "produce",
      tag: "Best Seller",
      price: 320,
      mrp: 380,
      netQuantity: "1 kg",
      unit: "1 kg",
      sku: "NB-GRN-KNR-1KG",
      barcode: "8906123401001",
      packedOn: "June 2026",
      bestBefore: "June 2027",
      ingredients: "100% Kala Namak (Buddha) Rice — naturally grown",
      specifications: [
        "Variety: Kala Namak / Buddha rice",
        "Type: Raw / aromatic indigenous rice",
        "Processing: Cleaned & packed",
        "Allergen: None declared",
      ],
      packagingText: [
        "Know Your Farmer. Know Your Food.",
        "Naturally Grown · Farm Direct",
        "No artificial colours | No preservatives",
        "Store in a cool, dry place away from sunlight",
        "For complaints: nastroblu.eatbetter@gmail.com",
      ],
      storage: "Airtight container in a cool, dry place",
      origin: "India — farm-direct supply",
      sizes: [
        { label: "500 g", price: 180, sku: "NB-GRN-KNR-500G" },
        { label: "1 kg", price: 320, sku: "NB-GRN-KNR-1KG" },
        { label: "5 kg", price: 1450, sku: "NB-GRN-KNR-5KG" },
      ],
      blurb: "Buddha rice · Aromatic · Low GI",
      description:
        "Naturally grown Kala Namak (Buddha) rice — fragrant, soft-cooking, and sourced from farmers who still grow this indigenous variety the traditional way. Perfect for daily meals and festive biryanis.",
      image: "assets/products/rice.jpg",
      rating: 4.9,
      reviews: 86,
    },
    {
      id: "yellow-jowar",
      name: "Yellow Jowar",
      brand: "Nastro Blu",
      category: "produce",
      tag: "Must Try",
      price: 110,
      mrp: 140,
      netQuantity: "1 kg",
      unit: "1 kg",
      sku: "NB-GRN-YJW-1KG",
      barcode: "8906123401002",
      packedOn: "June 2026",
      bestBefore: "June 2027",
      ingredients: "100% Yellow Jowar (Sorghum) grain",
      specifications: [
        "Grain: Yellow sorghum / jowar",
        "Gluten: Naturally gluten-free",
        "Use: Roti, porridge, millet mixes",
      ],
      packagingText: [
        "Indigenous seed · Naturally grown",
        "Gluten-free whole grain",
        "Store cool & dry",
      ],
      storage: "Cool, dry place in airtight pack",
      origin: "India",
      sizes: [
        { label: "1 kg", price: 110, sku: "NB-GRN-YJW-1KG" },
        { label: "2 kg", price: 210, sku: "NB-GRN-YJW-2KG" },
      ],
      blurb: "Gluten-free · Stone-ready · Native sorghum",
      description:
        "Sun-dried yellow jowar (sorghum) from indigenous seed lines. Rich in fibre and naturally gluten-free — ideal for rotis, porridge, and millet mixes.",
      image: "assets/products/jowar.jpg",
      rating: 4.8,
      reviews: 42,
    },
    {
      id: "paigambari-wheat",
      name: "Paigambari Wheat",
      brand: "Nastro Blu",
      category: "produce",
      tag: null,
      price: 95,
      mrp: 120,
      netQuantity: "1 kg",
      unit: "1 kg",
      sku: "NB-GRN-PGW-1KG",
      barcode: "8906123401003",
      packedOn: "June 2026",
      bestBefore: "June 2027",
      ingredients: "100% Paigambari Wheat whole grain",
      specifications: [
        "Variety: Paigambari desi wheat",
        "Best for: Soft chapati / roti",
        "Form: Whole wheat grain",
      ],
      packagingText: [
        "Desi wheat · Farm direct",
        "Naturally grown produce",
        "MRP inclusive of all taxes (where applicable)",
      ],
      storage: "Cool, dry place",
      origin: "India",
      sizes: [
        { label: "1 kg", price: 95, sku: "NB-GRN-PGW-1KG" },
        { label: "5 kg", price: 440, sku: "NB-GRN-PGW-5KG" },
      ],
      blurb: "Soft rotis · Desi wheat · Farm-direct",
      description:
        "Paigambari wheat — a soft, desi variety loved for fluffy chapati. Grown without chemical shortcuts and packed fresh for your kitchen.",
      image: "assets/products/wheat.jpg",
      rating: 4.7,
      reviews: 58,
    },
    {
      id: "khapli-wheat",
      name: "Khapli Wheat (Emmer)",
      brand: "Nastro Blu",
      category: "produce",
      tag: "Trending",
      price: 185,
      mrp: 220,
      netQuantity: "1 kg",
      unit: "1 kg",
      sku: "NB-GRN-KHW-1KG",
      barcode: "8906123401004",
      packedOn: "June 2026",
      bestBefore: "June 2027",
      ingredients: "100% Khapli (Emmer) Wheat",
      specifications: [
        "Ancient grain / emmer wheat",
        "Lower gluten vs modern wheat",
        "Higher fibre profile",
      ],
      packagingText: [
        "Support Indigenous Seeds",
        "Ancient grain · Naturally grown",
        "Eat Better — Nastro Blu",
      ],
      storage: "Cool, dry place",
      origin: "India",
      sizes: [
        { label: "1 kg", price: 185, sku: "NB-GRN-KHW-1KG" },
        { label: "2 kg", price: 350, sku: "NB-GRN-KHW-2KG" },
        { label: "5 kg", price: 850, sku: "NB-GRN-KHW-5KG" },
      ],
      blurb: "Ancient grain · Low gluten · High fibre",
      description:
        "Khapli (emmer) wheat — an ancient indigenous grain with lower gluten and higher fibre than modern wheat. Slow-digested and deeply nourishing.",
      image: "assets/products/grains.jpg",
      rating: 4.9,
      reviews: 124,
    },
    {
      id: "khapli-atta",
      name: "Khapli Wheat Atta",
      brand: "Nastro Blu",
      category: "produce",
      tag: "New",
      price: 210,
      mrp: 250,
      netQuantity: "1 kg",
      unit: "1 kg",
      sku: "NB-GRN-KHA-1KG",
      barcode: "8906123401005",
      packedOn: "July 2026",
      bestBefore: "January 2027",
      ingredients: "100% Stone-ground Khapli (Emmer) Wheat flour",
      specifications: [
        "Milling: Stone-ground, small batch",
        "Texture: Soft roti atta",
        "GI: Relatively lower GI grain base",
      ],
      packagingText: [
        "Stone ground · Fresh milled feel",
        "No maida blend",
        "Keep refrigerated after opening in humid weather",
      ],
      storage: "Airtight; refrigerate in humid climates",
      origin: "India",
      sizes: [
        { label: "1 kg", price: 210, sku: "NB-GRN-KHA-1KG" },
        { label: "2 kg", price: 400, sku: "NB-GRN-KHA-2KG" },
        { label: "5 kg", price: 950, sku: "NB-GRN-KHA-5KG" },
      ],
      blurb: "Stone-ground · Soft rotis · Low GI",
      description:
        "Stone-ground Khapli atta milled in small batches. Soft rotis with a nutty aroma — a smarter everyday swap for refined flour.",
      image: "assets/products/atta.jpg",
      rating: 4.8,
      reviews: 97,
    },
    {
      id: "groundnut-oil",
      name: "Cold-Pressed Groundnut Oil",
      brand: "Nastro Blu",
      category: "oils",
      tag: "Best Seller",
      price: 425,
      mrp: 480,
      netQuantity: "1 L",
      unit: "1 L",
      sku: "NB-OIL-GND-1L",
      barcode: "8906123402001",
      packedOn: "July 2026",
      bestBefore: "July 2027",
      ingredients: "100% Cold-pressed Groundnut (Peanut) Oil",
      specifications: [
        "Process: Cold-pressed in-store",
        "Filter: Single-filtered, unrefined",
        "Allergen: Contains peanut",
      ],
      packagingText: [
        "Cold pressed in Bagh Amberpet store",
        "Unrefined · Full aroma",
        "Not a blended oil",
        "Allergen warning: Peanut",
      ],
      storage: "Away from heat & direct sunlight",
      origin: "Pressed in Hyderabad",
      sizes: [
        { label: "500 ml", price: 230, sku: "NB-OIL-GND-500ML" },
        { label: "1 L", price: 425, sku: "NB-OIL-GND-1L" },
        { label: "5 L", price: 1990, sku: "NB-OIL-GND-5L" },
      ],
      blurb: "Single-pressed in-store · Full aroma",
      description:
        "Native groundnuts cold-pressed in our Bagh Amberpet store. Single-filtered, unrefined, and rich in natural flavour — for tadka, frying, and everyday cooking.",
      image: "assets/products/oil.jpg",
      rating: 4.9,
      reviews: 210,
    },
    {
      id: "sesame-oil",
      name: "Cold-Pressed Sesame Oil",
      brand: "Nastro Blu",
      category: "oils",
      tag: null,
      price: 480,
      mrp: 540,
      netQuantity: "1 L",
      unit: "1 L",
      sku: "NB-OIL-SES-1L",
      barcode: "8906123402002",
      packedOn: "July 2026",
      bestBefore: "July 2027",
      ingredients: "100% Cold-pressed Sesame (Gingelly) Oil",
      specifications: [
        "Process: Slow cold-pressed",
        "Style: Unrefined gingelly oil",
        "Use: Cooking, traditional rituals",
      ],
      packagingText: [
        "Gingelly / sesame oil",
        "Cold pressed · Unrefined",
        "Store upright after opening",
      ],
      storage: "Cool place, away from light",
      origin: "Pressed in Hyderabad",
      sizes: [
        { label: "500 ml", price: 260, sku: "NB-OIL-SES-500ML" },
        { label: "1 L", price: 480, sku: "NB-OIL-SES-1L" },
      ],
      blurb: "Gingelly · Unrefined · In-store pressed",
      description:
        "Slow cold-pressed sesame (gingelly) oil with a deep nutty character. Ideal for South Indian cooking, hair care rituals, and traditional recipes.",
      image: "assets/products/sesame.jpg",
      rating: 4.8,
      reviews: 76,
    },
    {
      id: "mustard-oil",
      name: "Cold-Pressed Mustard Oil",
      brand: "Nastro Blu",
      category: "oils",
      tag: "Must Try",
      price: 395,
      mrp: 450,
      netQuantity: "1 L",
      unit: "1 L",
      sku: "NB-OIL-MST-1L",
      barcode: "8906123402003",
      packedOn: "July 2026",
      bestBefore: "July 2027",
      ingredients: "100% Cold-pressed Black Mustard Oil",
      specifications: [
        "Seed: Black mustard",
        "Process: Cold-pressed, single-filtered",
        "Character: Pungent & clean",
      ],
      packagingText: [
        "Cold pressed mustard oil",
        "For cooking & pickles",
        "Shake gently if natural sediment appears",
      ],
      storage: "Cool, dark place",
      origin: "Pressed in Hyderabad",
      sizes: [
        { label: "500 ml", price: 210, sku: "NB-OIL-MST-500ML" },
        { label: "1 L", price: 395, sku: "NB-OIL-MST-1L" },
        { label: "5 L", price: 1850, sku: "NB-OIL-MST-5L" },
      ],
      blurb: "Black mustard · Sharp & clean",
      description:
        "Cold-pressed black mustard oil — pungent, clean, and single-filtered. Perfect for pickles, sabzis, and winter cooking.",
      image: "assets/products/mustard-oil.jpg",
      rating: 4.7,
      reviews: 64,
    },
    {
      id: "coconut-oil",
      name: "Virgin Coconut Oil",
      brand: "Nastro Blu",
      category: "oils",
      tag: null,
      price: 450,
      mrp: 520,
      netQuantity: "500 ml",
      unit: "500 ml",
      sku: "NB-OIL-CCO-500ML",
      barcode: "8906123402004",
      packedOn: "July 2026",
      bestBefore: "July 2027",
      ingredients: "100% Virgin Coconut Oil (cold-pressed)",
      specifications: [
        "Type: Virgin / unrefined",
        "Source: Fresh copra",
        "Use: Cooking, skin & hair",
      ],
      packagingText: [
        "Virgin coconut oil",
        "No refining · No fragrance added",
        "May solidify below room temperature — natural",
      ],
      storage: "Room temperature; solidifies when cool",
      origin: "India",
      sizes: [
        { label: "250 ml", price: 240, sku: "NB-OIL-CCO-250ML" },
        { label: "500 ml", price: 450, sku: "NB-OIL-CCO-500ML" },
      ],
      blurb: "Cold-pressed · Unrefined · Multi-use",
      description:
        "Virgin coconut oil cold-pressed from fresh copra. Pure enough for cooking, skin, and hair — no refining, no fragrance.",
      image: "assets/products/coconut-oil.jpg",
      rating: 4.9,
      reviews: 55,
    },
    {
      id: "forest-raw-honey",
      name: "Forest Raw Honey",
      brand: "Nastro Blu",
      category: "honey",
      tag: "New",
      price: 450,
      mrp: 520,
      netQuantity: "500 g",
      unit: "500 g",
      sku: "NB-HNY-FRH-500G",
      barcode: "8906123403004",
      packedOn: "July 2026",
      bestBefore: "July 2028",
      ingredients: "100% Forest Raw Honey — unprocessed",
      specifications: [
        "Origin: Kerala Western Ghats",
        "Type: Raw / unprocessed forest honey",
        "Form: Natural liquid honey in glass jar",
        "No added sugar · No artificial flavour",
      ],
      packagingText: [
        "FOREST RAW HONEY FROM KERALA WESTERN GHATS",
        "NASTRO BLU · EAT BETTER",
        "Call & WhatsApp +91 90630 48255 / +91 40 4540 8385",
        "Follow @nastroblu.eatbetter",
        "2-2-18/15/C, Plot No-10, Durgabai Deshmukh Colony, Bagh Amberpet, HYD-500013",
      ],
      storage: "Cool, dry place away from direct sunlight",
      origin: "Kerala Western Ghats",
      sizes: [
        { label: "250 g", price: 260, sku: "NB-HNY-FRH-250G" },
        { label: "500 g", price: 450, sku: "NB-HNY-FRH-500G" },
      ],
      blurb: "Kerala Western Ghats · Raw · Unprocessed",
      description:
        "Forest raw honey sourced from Kerala’s Western Ghats — amber, aromatic, and unprocessed. A pure pantry staple for everyday wellness and traditional recipes.",
      image: "assets/products/forest-honey.png",
      rating: 4.9,
      reviews: 38,
    },
    {
      id: "salem-turmeric",
      name: "Salem Turmeric Powder",
      brand: "Nastro Blu",
      category: "spices",
      tag: "Best Seller",
      price: 170,
      mrp: 210,
      netQuantity: "200 g",
      unit: "200 g",
      sku: "NB-SPC-STM-200G",
      barcode: "8906123403001",
      packedOn: "June 2026",
      bestBefore: "June 2028",
      ingredients: "100% Salem Turmeric (Curcuma longa) powder",
      specifications: [
        "Origin style: Salem / single-origin sourcing",
        "Form: Fine powder, stone-ground feel",
        "Colour: Naturally vibrant yellow-orange",
      ],
      packagingText: [
        "Kerala / South Indian spice pantry",
        "No added colour · No fillers",
        "Prefer Naturally Grown Produce",
      ],
      storage: "Airtight, away from moisture",
      origin: "Salem region supply chain",
      sizes: [
        { label: "100 g", price: 95, sku: "NB-SPC-STM-100G" },
        { label: "200 g", price: 170, sku: "NB-SPC-STM-200G" },
        { label: "500 g", price: 380, sku: "NB-SPC-STM-500G" },
      ],
      blurb: "Single-origin · High curcumin · Vibrant colour",
      description:
        "Single-origin Salem turmeric, sun-dried and stone-ground. Bright colour, earthy aroma, and naturally high curcumin — the backbone of an honest kitchen.",
      image: "assets/products/turmeric.jpg",
      rating: 4.9,
      reviews: 188,
    },
    {
      id: "kerala-pepper",
      name: "Kerala Black Pepper",
      brand: "Nastro Blu",
      category: "spices",
      tag: null,
      price: 180,
      mrp: 220,
      netQuantity: "100 g",
      unit: "100 g",
      sku: "NB-SPC-KBP-100G",
      barcode: "8906123403002",
      packedOn: "June 2026",
      bestBefore: "June 2028",
      ingredients: "100% Whole Black Peppercorns",
      specifications: [
        "Region: Kerala / Malabar style",
        "Form: Whole peppercorns",
        "Grind fresh for best aroma",
      ],
      packagingText: [
        "Kerala Spices",
        "Whole pepper · Farm linked",
        "Crush or grind before use",
      ],
      storage: "Airtight jar",
      origin: "Kerala",
      sizes: [
        { label: "100 g", price: 180, sku: "NB-SPC-KBP-100G" },
        { label: "250 g", price: 420, sku: "NB-SPC-KBP-250G" },
      ],
      blurb: "Malabar coast · Whole peppercorns",
      description:
        "Bold Malabar black pepper from Kerala farms. Freshly sourced whole peppercorns with sharp heat and floral notes.",
      image: "assets/products/pepper.jpg",
      rating: 4.8,
      reviews: 71,
    },
    {
      id: "kerala-spice-box",
      name: "Kerala Everyday Spice Box",
      brand: "Nastro Blu",
      category: "spices",
      tag: "New",
      price: 650,
      mrp: 780,
      netQuantity: "Assorted gift box",
      unit: "Box",
      sku: "NB-SPC-BOX-001",
      barcode: "8906123403003",
      packedOn: "July 2026",
      bestBefore: "See individual packs inside",
      ingredients: "Turmeric, Chilli, Black Pepper, Coriander — see inner packs",
      specifications: [
        "Contents: 4 everyday Kerala staples",
        "Format: Gift / pantry starter box",
        "Ideal for: Home kitchens & gifting",
      ],
      packagingText: [
        "Kerala Everyday Spice Box",
        "Eat Better · Nastro Blu",
        "Check inner labels for net wt & dates",
      ],
      storage: "Cool, dry place",
      origin: "Assembled in Hyderabad",
      sizes: [{ label: "Gift box", price: 650, sku: "NB-SPC-BOX-001" }],
      blurb: "Turmeric · Chilli · Pepper · Coriander",
      description:
        "A curated set of Kerala staples — turmeric, chilli, pepper, and coriander — packed for everyday cooking and gifting.",
      image: "assets/products/spices.jpg",
      rating: 4.8,
      reviews: 33,
    },
    {
      id: "kashmiri-almonds",
      name: "Kashmiri Almonds",
      brand: "Nastro Blu",
      category: "dryfruits",
      tag: "Trending",
      price: 450,
      mrp: 520,
      netQuantity: "250 g",
      unit: "250 g",
      sku: "NB-DFR-ALM-250G",
      barcode: "8906123404001",
      packedOn: "July 2026",
      bestBefore: "January 2027",
      ingredients: "100% Kashmiri Almonds (Badam)",
      specifications: [
        "Grade: Hand-sorted premium",
        "Form: Whole almonds",
        "Allergen: Tree nut",
      ],
      packagingText: [
        "Kashmiri Dry Fruits",
        "Contains tree nuts",
        "Soak overnight for softer bite",
      ],
      storage: "Airtight; refrigerate in warm weather",
      origin: "Kashmir supply",
      sizes: [
        { label: "250 g", price: 450, sku: "NB-DFR-ALM-250G" },
        { label: "500 g", price: 860, sku: "NB-DFR-ALM-500G" },
      ],
      blurb: "Hand-sorted · Sweet & crunchy",
      description:
        "Premium Kashmiri almonds — hand-sorted for size and sweetness. Soak overnight or roast lightly for a wholesome snack.",
      image: "assets/products/nuts.jpg",
      rating: 4.9,
      reviews: 92,
    },
    {
      id: "kashmiri-walnuts",
      name: "Kashmiri Walnuts",
      brand: "Nastro Blu",
      category: "dryfruits",
      tag: null,
      price: 520,
      mrp: 600,
      netQuantity: "250 g",
      unit: "250 g",
      sku: "NB-DFR-WLN-250G",
      barcode: "8906123404002",
      packedOn: "July 2026",
      bestBefore: "January 2027",
      ingredients: "100% Kashmiri Walnut Kernels",
      specifications: [
        "Form: Shelled kernels",
        "Profile: Buttery, omega-rich",
        "Allergen: Tree nut",
      ],
      packagingText: [
        "Kashmiri walnuts",
        "Contains tree nuts",
        "Best consumed fresh after opening",
      ],
      storage: "Refrigerate after opening",
      origin: "Kashmir supply",
      sizes: [
        { label: "250 g", price: 520, sku: "NB-DFR-WLN-250G" },
        { label: "500 g", price: 980, sku: "NB-DFR-WLN-500G" },
      ],
      blurb: "Fresh kernels · Brain food classic",
      description:
        "Fresh Kashmiri walnut kernels with a clean, buttery bite. Rich in omega-3s — a pantry essential for winter and wellness.",
      image: "assets/products/nuts.jpg",
      rating: 4.8,
      reviews: 61,
    },
    {
      id: "cashews",
      name: "Whole Cashews",
      brand: "Nastro Blu",
      category: "dryfruits",
      tag: null,
      price: 380,
      mrp: 440,
      netQuantity: "250 g",
      unit: "250 g",
      sku: "NB-DFR-CSH-250G",
      barcode: "8906123404003",
      packedOn: "July 2026",
      bestBefore: "January 2027",
      ingredients: "100% Whole Cashew Nuts",
      specifications: [
        "Grade: W320 style whole cashews",
        "Form: Whole, creamy",
        "Allergen: Tree nut / cashew",
      ],
      packagingText: [
        "Whole cashews",
        "Contains cashew nuts",
        "No broken bits preferred pack",
      ],
      storage: "Airtight, cool place",
      origin: "India",
      sizes: [
        { label: "250 g", price: 380, sku: "NB-DFR-CSH-250G" },
        { label: "500 g", price: 720, sku: "NB-DFR-CSH-500G" },
      ],
      blurb: "W320 grade · Creamy & whole",
      description:
        "Whole creamy cashews selected for snacking, sweets, and festival cooking. No broken bits, no additives.",
      image: "assets/products/grains.jpg",
      rating: 4.7,
      reviews: 48,
    },
    {
      id: "kaju-katli",
      name: "Kaju Katli",
      brand: "Nastro Blu",
      category: "sweets",
      tag: "Best Seller",
      price: 450,
      mrp: 520,
      netQuantity: "250 g",
      unit: "250 g",
      sku: "NB-SWT-KKL-250G",
      barcode: "8906123405001",
      packedOn: "Made fresh — ask batch date in store",
      bestBefore: "Consume within 7–10 days of packing",
      ingredients: "Cashew nuts, cane sugar, ghee (as used in preparation)",
      specifications: [
        "Style: Traditional kaju katli",
        "Sweetener: Real sugar (no artificial sweetener)",
        "Clean label: No silver leaf, no artificial colour/essence",
      ],
      packagingText: [
        "No artificial colours · No essence",
        "No preservatives · No silver leaf",
        "Traditional Sweets — made fresh",
        "Contains nuts & dairy",
      ],
      storage: "Cool place; refrigerate in warm weather",
      origin: "Made in Hyderabad store kitchen",
      sizes: [
        { label: "250 g", price: 450, sku: "NB-SWT-KKL-250G" },
        { label: "500 g", price: 860, sku: "NB-SWT-KKL-500G" },
      ],
      blurb: "No silver leaf · Real cashew · Fresh",
      description:
        "Classic kaju katli made in-house with real cashews and cane sugar — no artificial colours, essence, preservatives, or silver leaf.",
      image: "assets/products/sweets.jpg",
      rating: 4.9,
      reviews: 156,
    },
    {
      id: "besan-ladoo",
      name: "Besan Ladoo",
      brand: "Nastro Blu",
      category: "sweets",
      tag: null,
      price: 220,
      mrp: 260,
      netQuantity: "250 g",
      unit: "250 g",
      sku: "NB-SWT-BLD-250G",
      barcode: "8906123405002",
      packedOn: "Made fresh — ask batch date in store",
      bestBefore: "Consume within 10–12 days of packing",
      ingredients: "Besan (gram flour), ghee, sugar / jaggery (batch dependent)",
      specifications: [
        "Method: Slow-roasted besan",
        "Fat: Bilona ghee aroma profile",
        "Option: Jaggery-sweetened batches on request",
      ],
      packagingText: [
        "Traditional sweet · Made fresh",
        "No artificial colours / essence",
        "Contains dairy & gluten (besan/wheat traces if shared kitchen)",
      ],
      storage: "Airtight container",
      origin: "Made in Hyderabad",
      sizes: [
        { label: "250 g", price: 220, sku: "NB-SWT-BLD-250G" },
        { label: "500 g", price: 420, sku: "NB-SWT-BLD-500G" },
      ],
      blurb: "Ghee-roasted · Jaggery option available",
      description:
        "Slow-roasted besan ladoos with bilona ghee aroma. Ask us for jaggery-sweetened batches when available.",
      image: "assets/products/ladoo.jpg",
      rating: 4.8,
      reviews: 89,
    },
    {
      id: "chakli",
      name: "Traditional Chakli",
      brand: "Nastro Blu",
      category: "sweets",
      tag: "Must Try",
      price: 180,
      mrp: 210,
      netQuantity: "200 g",
      unit: "200 g",
      sku: "NB-SNK-CHK-200G",
      barcode: "8906123405003",
      packedOn: "Made fresh — ask batch date in store",
      bestBefore: "Best within 15 days of packing",
      ingredients: "Millet / rice flour blend, spices, cold-pressed oil (for frying), salt",
      specifications: [
        "Fry medium: Nastro Blu cold-pressed oil",
        "Style: Traditional chakli / murukku family",
        "Texture: Crisp",
      ],
      packagingText: [
        "Fried in cold-pressed oil",
        "Traditional snacks",
        "Keep away from moisture",
      ],
      storage: "Airtight tin / jar",
      origin: "Made in Hyderabad",
      sizes: [
        { label: "200 g", price: 180, sku: "NB-SNK-CHK-200G" },
        { label: "400 g", price: 340, sku: "NB-SNK-CHK-400G" },
      ],
      blurb: "Fried in cold-pressed oil",
      description:
        "Crisp chakli made with millet flour and fried in our own cold-pressed oil — clean crunch without the usual aftertaste.",
      image: "assets/products/snacks.jpg",
      rating: 4.7,
      reviews: 67,
    },
    {
      id: "makhana",
      name: "Roasted Makhana",
      brand: "Nastro Blu",
      category: "sweets",
      tag: null,
      price: 160,
      mrp: 190,
      netQuantity: "100 g",
      unit: "100 g",
      sku: "NB-SNK-MKH-100G",
      barcode: "8906123405004",
      packedOn: "July 2026",
      bestBefore: "January 2027",
      ingredients: "Fox nuts (Makhana), edible salt, seasoning (as applicable)",
      specifications: [
        "Process: Roasted",
        "Seasoning: Lightly salted",
        "Snack style: Light & crunchy",
      ],
      packagingText: [
        "Roasted makhana",
        "Guilt-free evening snack",
        "Reseal after opening",
      ],
      storage: "Airtight after opening",
      origin: "India",
      sizes: [
        { label: "100 g", price: 160, sku: "NB-SNK-MKH-100G" },
        { label: "250 g", price: 360, sku: "NB-SNK-MKH-250G" },
      ],
      blurb: "Lightly salted · Guilt-free crunch",
      description:
        "Fox nuts roasted and lightly seasoned. A clean evening snack that travels well and stays crisp.",
      image: "assets/products/snacks.jpg",
      rating: 4.6,
      reviews: 40,
    },
    {
      id: "a2-ghee-500",
      name: "Bilona A2 Desi Cow Ghee",
      brand: "Nastro Blu",
      category: "ghee",
      tag: "Best Seller",
      price: 950,
      mrp: 1100,
      netQuantity: "500 ml",
      unit: "500 ml",
      sku: "NB-DRY-A2G-500ML",
      barcode: "8906123406001",
      packedOn: "July 2026",
      bestBefore: "July 2027",
      ingredients: "100% Bilona-method Ghee from A2 Desi Cow Milk",
      specifications: [
        "Method: Traditional bilona (cultured / hand-churned style)",
        "Milk: A2 desi cow",
        "Character: Golden, aromatic",
      ],
      packagingText: [
        "Bilona A2 Desi Cow Ghee",
        "Dairy & Ghee — Eat Better",
        "No additives · No preservatives",
        "Use a dry spoon",
      ],
      storage: "Room temperature; away from moisture",
      origin: "Prepared for Nastro Blu, Hyderabad",
      sizes: [
        { label: "250 ml", price: 520, sku: "NB-DRY-A2G-250ML" },
        { label: "500 ml", price: 950, sku: "NB-DRY-A2G-500ML" },
        { label: "1 L", price: 1850, sku: "NB-DRY-A2G-1L" },
      ],
      blurb: "Bilona-churned · A2 desi cow · Golden",
      description:
        "Traditional bilona-method ghee from A2 desi cow milk — cultured, hand-churned, and slow-cooked over firewood heat for that grandmother's-kitchen aroma.",
      image: "assets/products/ghee.jpg",
      rating: 5.0,
      reviews: 240,
    },
    {
      id: "a2-milk",
      name: "A2 Desi Cow Milk",
      brand: "Nastro Blu",
      category: "ghee",
      tag: "Store Pickup",
      price: 90,
      mrp: 100,
      netQuantity: "1 L",
      unit: "1 L",
      sku: "NB-DRY-A2M-1L",
      barcode: "8906123406002",
      packedOn: "Daily fresh — date on bottle / pouch",
      bestBefore: "Consume within 24–48 hrs refrigerated",
      ingredients: "100% A2 Desi Cow Milk",
      specifications: [
        "Type: Fresh milk",
        "Channel: Store pickup / select Hyderabad routes",
        "Availability: Confirm on WhatsApp same day",
      ],
      packagingText: [
        "A2 Desi Cow Milk",
        "Keep refrigerated",
        "Farm-linked · Hyderabad",
      ],
      storage: "Refrigerate at 4°C or below",
      origin: "Hyderabad farm-linked supply",
      sizes: [{ label: "1 L", price: 90, sku: "NB-DRY-A2M-1L" }],
      blurb: "Fresh · Farm-linked · Hyderabad only",
      description:
        "Fresh A2 desi cow milk available for store pickup and select Hyderabad delivery routes. Message us on WhatsApp for today's availability.",
      image: "assets/products/ghee.jpg",
      rating: 4.9,
      reviews: 112,
    },
  ],
};
